### ISSUE TITLE
[Quick Tour] - Run the composer is not clearly explained

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-www#1004]
**Description:**
1. How to run composer is not clearly explained. For windows, it can be started by double click on the composer in the bin folder.
2. In "create a new package", c is declared twice.

**Suggested Labels:**
Type/doc

**Affected Product Version:**  
Ballerina Version - 0.975.1

**Comment by namila007** [comment]
If you dont have php composer, you can run it buy cmd typing `composer` 
Remove the `c` decleration inside the loop

**Comment by anupama-pathirage** [comment]
From ballerina V 0.990.0, we have removed the support for composer. We are supporting Ballerina VSCode plugin and Intellij IDEA plugin now.
