### ISSUE TITLE
[Quick Tour - Suggestion]Use git bash to exicute curl commands

### ISSUE THREAD

**Issue by jayamaljayamaha** [ballerina-platform/ballerina-www#1027]
**Description:**
When reading these issues, I could notice that many issues have arisen because of curl commands. but instead of curl, we can use gitbash to achieve that target. No need to install curl separately to your machine and set environment variables, if you used git before there is a git bash in your machine.

I used gitBash and I didn't get any errors in git commands. Worked successfully. I suggest everyone it is better to use gitbash because it is an easy way than installing curl separately 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
windows
**Steps to reproduce:**

**Related Issues:**

**Comment by Nashaath** [comment]
Thanks for the suggestion, Jayamal!
When trying out the quick tour, it is up to the user to use a preferred client. 
Can be Git bash, curl or any other client depending on what each user is familiar or find easy to use :)

**Comment by Nashaath** [comment]
You can send in your suggestions to the Ballerina developer mailing list [1].
[1] https://ballerina.io/community/#developer-resources
