### ISSUE TITLE
[Quick - Tour] Curl command error in creating service.bal

### ISSUE THREAD

**Issue by mster3313** [ballerina-platform/ballerina-www#1042]
**Description:**
In instruction #8 curl command doesnt work. It has to be modified as follows

curl -d "{'firstNumber':10,'secondNumber':200,'operation':'add'}" "http://localhost:9090/calculator/operation" -H "Content-Type:application/json"

or a json data file can be attached like follows

curl -d "@data.json" -X POST "http://localhost:9090/calculator/operation" -H "Content-Type:application/json"

data.json
--------------------------------
{
  "firstNumber":10,
  "secondNumber":200,
   "operation":"add"
}
---------------------------------

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Ballerina 0.980.0
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

**OS, DB, other environment details and versions:**    
Windows 10

**Comment by pranavan15** [comment]
@mster3313 Could you please point me to the exact link to which you are referring?

**Comment by anupama-pathirage** [comment]
@pranavan15 I think this issue is about the service on https://ballerina.io/community-program/ page

**Comment by pranavan15** [comment]
Tested the current version, which works fine. Last commit that modified this section belongs to the PR https://github.com/ballerina-platform/ballerina-www/pull/1008.

**Comment by pranavan15** [comment]
@mster3313 Closing this issue as per the above comment. Please re-open if you have any concerns.
