### ISSUE TITLE
When I tried to follow the quick tour and create a new package, syntax error occurs in main.bal of calculator package

### ISSUE THREAD

**Issue by AathmanT** [ballerina-platform/ballerina-www#1066]
**Description:**
I copied the code for main.bal in calculator package and I got error redeclared symbol calculator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.975.1

**OS, DB, other environment details and versions:**    
Windows 10
**Steps to reproduce:**
Follow the quick tour to create a package
![screenshot 7](https://user-images.githubusercontent.com/35717580/43242824-d8ef2e1e-90c0-11e8-806e-41cd2b240b21.png)
![screenshot 6](https://user-images.githubusercontent.com/35717580/43242825-d92c1a36-90c0-11e8-870c-0943ea70bc4b.png)

**Related Issues:**
I tried to delete the package calculator;    line 1  and then ran the code but I got the error redeclared symbol c.
![screenshot 11](https://user-images.githubusercontent.com/35717580/43242984-ab96f054-90c1-11e8-801d-49ffd1b6d28d.png)

**Comment by ldclakmal** [comment]
Closing this issue as per the above comment. Please re-open if you have any concerns.
