### ISSUE TITLE
When I tried to run the client.bal in the client service for calculator in the quick tour I got the error ballerina: Oh no, something really went wrong. Bad. Sad. 

### ISSUE THREAD

**Issue by AathmanT** [ballerina-platform/ballerina-www#1067]
**Description:**
 I tried to run the client.bal in the client service for calculator in the quick tour I got the error ballerina: Oh no, something really went wrong. Bad. Sad. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.975.1

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**
Follow the quick tour to client service for calculator
![screenshot 10](https://user-images.githubusercontent.com/35717580/43243103-6c9d7b9c-90c2-11e8-956b-08465ea89da3.png)

**Related Issues:**

**Comment by ldclakmal** [comment]
This issue is not reproducible for the latest master. Hence closing the issue. Please re-open if you have any concerns.
