### ISSUE TITLE
 Mkdocs default theme obtained when built with latest Mkdocs version(1.0.4)

### ISSUE THREAD

**Issue by Shairam** [ballerina-platform/ballerina-www#1181]
We are currently using `theme_dir` option to specify the custom theme directory in the mkdocs.yml files. This option has been deprecated and replaced by `custom_dir`from the mkdocs version 0.17. As of version 1.0 this seems to raise an error thus giving the default mkdocs theme as the output instead of providing us with the custom ballerina theme.

**Comment by Thimuth** [comment]
We are using MkDocs 0.17 in our build systems hence keeping the `theme_dir` option atm. Once we upgrade the MkDocs version to 1.0 we'll be updating the .yml accordingly.
