### ISSUE TITLE
No method As getAsArray from .config files

### ISSUE THREAD

**Issue by Chamindu36** [ballerina-platform/ballerina-www#1204]
**Description:**
There is no defined method to get values as arrays from conf files (No method as getAsArray)

**Suggested Labels:**
Type/Improvement,

**Suggested Method Example:**
 config:getAsArray ("listenerConfig.keyStore.paths"),

**Affected Product Version:**
Ballerina 0.981.1

**OS, DB, other environment details and versions:**    
OS,DB

**Comment by Anoukh** [comment]
Closing this issue as it was moved to ballerina-lang repo
