### ISSUE TITLE
BBE sequence is wrong when click next example

### ISSUE THREAD

**Issue by ChinthakaSenanayaka** [ballerina-platform/ballerina-www#1218]
Description:
ballerina.io BBE example sequence and when going through 1 by 1 example then click next loads different example sequence.

This happened BBE Functions -> Functions as Entry Points. When hit next in the example then it loads Values and Types -> Values instead next example should be pointed to Object -> Object example.

The same happens for JSON / XML -> XML Access next goes to I/O -> Byte I/O instead next example should be pointed to Streams -> Streams example.

Object -> Abstract Objects and Streams -> Identify Trends next examples are also pointed to wrong BBE example sequence.

Steps to reproduce:
BBE List view:

![ballerinaio_bbe1](https://user-images.githubusercontent.com/2564122/46406834-7c22a800-c72a-11e8-8b5d-405f6f747223.png)

![ballerinaio_bbe2](https://user-images.githubusercontent.com/2564122/46406840-80e75c00-c72a-11e8-8c8e-61a6eafc4b44.png)

Next example wrong view:

![func_values](https://user-images.githubusercontent.com/2564122/46406855-8d6bb480-c72a-11e8-8d1b-2106197ffc91.png)

![xmlac_byteio](https://user-images.githubusercontent.com/2564122/46406859-9197d200-c72a-11e8-8d18-bb673e1d9207.png)

Affected Versions:
ballerina.io site BBE section

OS, DB, other environment details and versions:
N/A

Related Issues (optional):
N/A

Suggested Labels (optional):

Suggested Assignees (optional):

**Comment by jeradrutnam** [comment]
Fixed: #1245
