### ISSUE TITLE
Documentation example is not properly rendered

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-www#1222]
**Description:**
All the documentation in the example is added to the right-hand side.

<img width="1524" alt="ballerina by example documentation 2018-10-09 17-33-15" src="https://user-images.githubusercontent.com/4003115/46668290-96a4c780-cbe9-11e8-9950-fcfda160ee35.png">

These should be visible as it is to demonstrate documenting code.

**Comment by anupama-pathirage** [comment]
This is fixed now. 
![image](https://user-images.githubusercontent.com/16300038/51366343-0d1b6480-1b0b-11e9-8750-9e7a8f6a826f.png)
