### ISSUE TITLE
Ballerina Quick Tour - Calculator - main.bal throws error when executing 

### ISSUE THREAD

**Issue by CrowleyRajapakse** [ballerina-platform/ballerina-www#1342]
**Description:**

While trying to run the client code given in the quick guide, the following error is thrown. The errors are shown at lines 20 where the else statement is followed with a condition. Altering this to an else if or removing the condition seems to work.  

`error: home/calculator:0.0.1::main.bal:20:16: invalid token '('
error: home/calculator:0.0.1::main.bal:62:1: extraneous input '}'`

**Affected Product Version:**
Ballerina 0.990.2

**OS, DB, other environment details and versions:**
Mac OS 10.14.2

**Steps to reproduce:**
1.) Copy the following code and paste into the lib.bal file and save it.

`function add(float a, float b) returns (float) {
    return a + b;
}

function subtract(float a, float b) returns (float) {
    return a - b;
}

function multiply(float a, float b) returns (float) {
    return a * b;
}

function divide(float a, float b) returns (float) {
    return a / b;
}`

2. ) Copy the following code and paste it into the main.bal file and save it.

`import ballerina/io;

public function main() {

    int operation = 0;
    while (operation != 5) {
        // print options menu to choose from
        io:println("Select operation.");
        io:println("1. Add");
        io:println("2. Subtract");
        io:println("3. Multiply");
        io:println("4. Divide");
        io:println("5. Exit");

        // read user's choice
        string val = io:readln("Enter choice 1 - 5: ");
        var choice = int.convert(val);
        if (choice is int) {
            operation = choice;
        } else (choice is error) {
            io:println("Invalid choice \n");
            continue;
        }

        if (operation == 5) {
            break;
        } else if (operation < 1 || operation > 5) {
            io:println("Invalid choice \n");
            continue;
        }

        // Read two numbers from user to be used for calculator operations
        var input1 = io:readln("Enter first number: ");
        var num1 = float.convert(input1);
        float firstNumber = 0;
        if (num1 is float) {
            firstNumber = num1;
        } else {
            io:println("Invalid first number \n");
            continue;
        }
        var input2 = io:readln("Enter second number: ");
        var num2 = float.convert(input2);
        float secondNumber = 0;
        if (num2 is float) {
            secondNumber = num2;
        } else {
            io:println("Invalid second number \n");
            continue;
        }
        // Execute calculator operations based on user's choice
        if (operation == 1) {
            io:print("Add result: ");
            io:println(add(firstNumber, secondNumber));
        } else if (operation == 2) {
            io:print("Subtract result: ");
            io:println(subtract(firstNumber, secondNumber));
        } else {
            io:println("Invalid choice");
        }
    }
}
`

**Related Issues:**
Quick tour Hello world code throws error when run #1341

**Comment by riyafa** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-www/pull/1343
