### ISSUE TITLE
[Docs] Ballerina Quick Tour improvements

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-www#1387]
**Areas that need to be fixed :**

- [ ] Set Up should be changed at **SETUP**
- [ ] Setup the Editor - This should be 'Setup Editors' 
- [ ] Include IDEA details
- [ ] VSCode Marketplace  (lets add the url and Shortcut to market place)
        Shortcut :  (Ctrl+Shift+X)

- [ ] VS Code plugin paragraph needs to be amended
        - You can find a plugin for Ballerina in the VS Code marketplace. ~~This helps read the .bal file using an ideal theme.~~
- [ ] **Annotation** we will have to re-word this 
_"Check if annotations work by entering some text and seeing proposed suggestions."_

**Comment by praneesha** [comment]
1. Set up is correct when we are referring to the action or the verb. Setup is the noun-form of it.
