### ISSUE TITLE
Get 404 when click on Create an issue link

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-www#1583]
**Description:**
1) Go to community page

https://v1-0.ballerina.io/community/

2) Click on here

![image](https://user-images.githubusercontent.com/4163165/64587780-0f923d80-d3be-11e9-9de1-23bd31d1c106.png)

3) Results 404. Link should be corrected to https://github.com/ballerina-platform/ballerina-lang/issues

**Comment by pubudu91** [comment]
Fixed with #1607
