### ISSUE TITLE
The 3 buttons under the heading "Learn the language and the libraries" in Learn page are all over the place

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-www#1587]
Refer to the image below
![Screenshot from 2019-09-10 14-04-00](https://user-images.githubusercontent.com/6260009/64597815-28a5e900-d3d4-11e9-85e5-6dd243b26aae.png)

**Comment by anupama-pathirage** [comment]
This is fixed now, hence closing the issue
