### ISSUE TITLE
There are no examples fro Observability, but the title is there

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-www#1591]
**Description:**
There isn't any example for Observability, but the title is there. We should either add an example, or remove the title;
<img width="411" alt="Screen Shot 2019-09-10 at 2 19 38 PM" src="https://user-images.githubusercontent.com/40016057/64598947-32c8e700-d3d6-11e9-8c3d-db50d6749dcf.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by grainier** [comment]
Examples are there, wonder why it doesn't show up in there.

```json
    {
        "title": "Observability",
        "column": 2,
        "category": "Working over the network",
        "samples": [{
                "name": "Distributed Tracing",
                "url": "tracing"
            },
            {
                "name": "Counter-Based Metrics",
                "url": "counter-metrics"
            },
            {
                "name": "Gauge-Based Metrics",
                "url": "gauge-metrics"
            }
        ]
    },
```

**Comment by grainier** [comment]
This should fix it: https://github.com/ballerina-platform/ballerina-lang/pull/18991
