### ISSUE TITLE
Git hub link shows 404 in Community page

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-www#1599]
**Description:**
When you click on the 'Edit on GitHub' it returs 404.

![image](https://user-images.githubusercontent.com/11239305/64609686-1a16fc00-d3eb-11e9-9253-e72d6e7f3bbd.png)

when you click on the link,

![image](https://user-images.githubusercontent.com/11239305/64609709-2a2edb80-d3eb-11e9-9441-874aa7a2d3b4.png)

**Comment by pubudu91** [comment]
Fixed with #1607
