### ISSUE TITLE
Links provided to help channels are not working

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-www#1601]
**Description:**
![image](https://user-images.githubusercontent.com/11239305/64609885-90b3f980-d3eb-11e9-8b7a-5df7fba49b0c.png)

When you click on the 2nd link, shows a page not found.

![image](https://user-images.githubusercontent.com/11239305/64609921-a88b7d80-d3eb-11e9-93ad-7829ab12764e.png)

**Comment by anupama-pathirage** [comment]
This is fixed now.
