### ISSUE TITLE
Links in Ballerina community page are not working

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-www#1604]
**Description:**
![image](https://user-images.githubusercontent.com/11239305/64610059-05873380-d3ec-11e9-9509-53f95c66f582.png)

![image](https://user-images.githubusercontent.com/11239305/64610309-9827d280-d3ec-11e9-9541-18fb35987a7b.png)

All these links are not working. All of them give 404.

**Comment by pubudu91** [comment]
Fixed with #1607
