### ISSUE TITLE
Reconsider "Developer First" image

### ISSUE THREAD

**Issue by michaelmior** [ballerina-platform/ballerina-www#1608]
**Description:**

The ["Developer First"](https://v1-0.ballerina.io/#Developer-First) image appears to be a woman massaging a male programmer while he works. I would suggest reconsidering the use of this image. It's disappointing to see a woman portrayed this way when it has nothing to do with software development.

**Comment by anupama-pathirage** [comment]
@michaelmior Thanks for reporting issues in ballerina. This has changed already with the following image.
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/16300038/65748182-f3fa9700-e120-11e9-85d0-f8e4a25607c0.png">

**Comment by michaelmior** [comment]
Thanks for the response!
