### ISSUE TITLE
Improvement to Quick Tour

### ISSUE THREAD

**Issue by ajanthan** [ballerina-platform/ballerina-www#716]
**Description:**

As a new learner, I started to learn the language by going through quick-tour. At the end of the quick-tour there are no suggestions to what to do next. It will be nice if there are possible next steps(link to more advanced resources) at the end of the quick-tour. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**   

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/723
