### ISSUE TITLE
Quick tour incorrectly refers to demo.bal while editing hello_service.bal

### ISSUE THREAD

**Issue by chintana** [ballerina-platform/ballerina-www#717]
**Description:**
Under https://ballerina.io/learn/quick-tour/#program-ballerina-to-send-a-tweet it continues to build on hello_service.bal example. And in the twitter connector section, when running the sample there's

`ballerina run demo.bal --config twitter.toml`

This should be,

` ballerina run hello_service.bal --config twitter.toml`

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/723
