### ISSUE TITLE
Reference Document to Learn all the Aspect of the language at Single place

### ISSUE THREAD

**Issue by ajanthan** [ballerina-platform/ballerina-www#718]
**Description:**
I could not find a reference document on language syntax and construct in https://ballerina.io/learn/. I came across `but` satement in one of the example but no way to get more detail about `but` syntax.  

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samisawso2** [comment]
We will be hosting the language spec soon that will address this issue.

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/731
