### ISSUE TITLE
Remove docker config registry "docker.abc.com" and defaults to local registry or use registry.hub.docker.com

### ISSUE THREAD

**Issue by chintana** [ballerina-platform/ballerina-www#720]
**Description:**

Quick tour docker config mention registry:"docker.abc.com". Is it possible to remove this and point to the local registry or use registry.hub.docker.com? - https://ballerina.io/learn/quick-tour/#deploying-on-docker

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/723
