### ISSUE TITLE
Quick tour docker section has a different file name when running docker sample

### ISSUE THREAD

**Issue by chintana** [ballerina-platform/ballerina-www#721]
**Description:**
Quick tour begins with hello_service.bal and in docker section https://ballerina.io/learn/quick-tour/#deploying-on-docker, filename is changed to hello_world_docker.bal.

`$> ballerina build hello_world_docker.bal`

This should be,

`$> ballerina build hello_service.bal`

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/723
