### ISSUE TITLE
Small typo in "How does Ballerina work?" section

### ISSUE THREAD

**Issue by madawas** [ballerina-platform/ballerina-www#724]
**Description:**
In the How does Ballerina work? > DEPLOYMENT ARCHITECTURE > IAAS section there is a small typo. 
https://ballerina.io/philosophy/

Please refer the screenshot below.
![screenshot from 2018-05-01 11-33-20](https://user-images.githubusercontent.com/4003137/39463088-7d706524-4d33-11e8-9076-add587a63a33.png)

**Suggested Labels:**
bug, Type/docs

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/725
