### ISSUE TITLE
Wrong information in quick-tour page of the ballerina.io site

### ISSUE THREAD

**Issue by Susankha** [ballerina-platform/ballerina-www#736]
**Description:**

Annotations section of the quick-tour page of the ballerina.io site contains wrong packaged import information. In the following image, you can see an import statement defined as "import ballerina/net.http;". But it should be "import ballerina/http"

![annotations](https://user-images.githubusercontent.com/6066040/39466948-1c9567f2-4d49-11e8-9266-b7de093449cb.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/740
