### ISSUE TITLE
Code given in (philosophy -> TYPE SAFE CONNECTORS) needs to be updated with new syntax

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-www#744]
$subject. Need to fix the API and syntax according to the new changes.

**Comment by uthaiyashankar** [comment]
Fix in https://github.com/ballerina-platform/ballerina-www/pull/760

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/760
