### ISSUE TITLE
https://ballerina.io/security/ page talks about WSO2 Security

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-www#748]
We need to modify the content.

**Comment by TylerJewell** [comment]
This page is accurate. Security reports are driven into the legal entity which is the same as the legal entity for our TOS, in this case is WSO2.

**Comment by uthaiyashankar** [comment]
Ack.

**Comment by uthaiyashankar** [comment]
There is a small disconnect. The description instructs to send the mail to security@ballerina.io, but the redirected page instructs to send to security@wso2.com. Won't this create confusion? Can we use security@wso2.com or security@ballerina.io in both places?

**Comment by samisawso2** [comment]
This issue has now been fixed.
