### ISSUE TITLE
Need to fill "https://ballerina.io/open-source/" -> CONTRIBUTE CODE

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-www#749]
"Contribution Guidelines" points to https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md , which is empty. Need to fill this.

**Comment by samgnaniah** [comment]
There is an open PR for this: https://github.com/ballerina-platform/ballerina-lang/pull/8306

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/8306
