### ISSUE TITLE
No page/resource linked to the FAQ on effective Ballerina code

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-www#756]
**Description:**
FAQ document contains the query given below. The answer is given for the query referencing some external page/resource but it is not properly linked. 

How do you write testable and maintainable code with Ballerina?

For details, see the [How to Write Effective Ballerina Code.](url)

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/757
