### ISSUE TITLE
https://ballerina.io/downloads/archived/ page - Need clear separation between the versions

### ISSUE THREAD

**Issue by amalrb** [ballerina-platform/ballerina-www#773]
**Description:**
In the "Archived Versions" page once you open up the "Release Notes", there is no clear separation between the release notes and the next archived version.

![image](https://user-images.githubusercontent.com/19181238/39506895-1b97c57e-4df9-11e8-8847-6770dc5adc93.png)

**Comment by jeradrutnam** [comment]
Fixed with #805
