### ISSUE TITLE
[Quick Tour] pre-requisite - docker should be intalled and started/restarted

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-www#776]
**Description:**
Can we mention like $subject for "Deploying on Docker" steps?

This is because to avoid any unnecessary issue occurring like below
- I tried the "Deploying on Docker"
- Docker was already up and running in windows
- After code changes, ballerina build hello_service.bal was failing

>PS C:\Users\wso2\Desktop\QuickGuide\project1> ballerina build hello_service.bal
error [docker plugin]: Unable to build docker image: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:46285->192.168.65.1:53: i/o timeout
ballerina: Oh no, something really went wrong. Bad. Sad.
There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.
We thank you for helping make us better dancers.

This has resolved once I restarted the docker, so can we improve our steps there?

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/784
