### ISSUE TITLE
[Quick Tour] Same command duplicates - improve adding as a tip/note

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-www#778]
**Description:**
As in below image, in both places we are giving same command. It would be good if we can add tip/note for section 2.

![tip](https://user-images.githubusercontent.com/15671620/39509075-8607ef0c-4e02-11e8-9026-01dd603e00f3.jpeg)

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-www/pull/784
