### ISSUE TITLE
Type Conversion Examples

### ISSUE THREAD

**Issue by jimk-osu** [ballerina-platform/ballerina-www#851]
**Description:**
Add more examples to [Type Conversion](https://ballerina.io/learn/by-example/type-conversion.html) in the By Example section.

Current Use Cases:  
- Create CSV out from `table` type.
  - this would be `table` to `string[]`
- `table` to `json` variable
  - `table` function `getNext()` outputs type `any` so this would be more `any` to `json`

**Suggested Labels:**
Content/Improvement

**Comment by samisawso2** [comment]
This is a good suggestion to be taken into account as a sample. 

The examples live in the https://github.com/ballerina-platform/ballerina-examples repo

**Comment by jimk-osu** [comment]
Thanks @samisawso2 ! 

If I have anything else I'll make the issue on the repo.

Closing this for issue cleanliness.
