### ISSUE TITLE
How to structure b7a code guide mention non-existant -s flag

### ISSUE THREAD

**Issue by chintana** [ballerina-platform/ballerina-www#858]
**Description:**
[How to structure Ballerina code guide](https://ballerina.io/learn/how-to-structure-ballerina-code/) mention -s flag for run (ballerina run -s file.bal) that's not there in Ballerina 0.970.1

```
$ ballerina run -s hello_service.bal
ballerina: unknown flag '-s'
Run 'ballerina help' for usage.
```

**Comment by NatashaWso2** [comment]
The "-s" flag is removed from [How to Structure Ballerina Code](https://ballerina.io/learn/how-to-structure-ballerina-code/), hence closing this issue
