### ISSUE TITLE
Quick Tour - simplify download instructions 

### ISSUE THREAD

**Issue by samisawso2** [ballerina-platform/ballerina-www#865]
Currently it says 

1. Go to [https://ballerina.io/](/) and click **Download Ballerina**. 

However, the user is already on the site, plus this step requires two actions to get to downloads. 

We can directly send them to 
https://ballerina.io/downloads

**Comment by samgnaniah** [comment]
This is fixed now.

https://ballerina.io/learn/quick-tour/
