### ISSUE TITLE
Quick Tour - point to setup instructions 

### ISSUE THREAD

**Issue by samisawso2** [ballerina-platform/ballerina-www#866]
The doc says 

Download Ballerina for your OS and follow the instructions given to set it up.

But it does not point to where the instructions are. It should either point to getting started guide or where to find those.

**Comment by samgnaniah** [comment]
Wouldn't these be covered by the installer itself for most part?

**Comment by samgnaniah** [comment]
This now points to Getting Started for more information.

https://ballerina.io/learn/quick-tour/
