### ISSUE TITLE
Default installation location is missing in Getting Started section for linux

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-www#869]
**Description:**
In Getting started [1], under the section "Installing on Linux" does not include the default installation location (i.e. /opt/ballerina)
But for other  OS types default location is mentioned. Also in the section "Uninstalling Ballerina", the default location is given as /usr/local/ballerina for linux. 

[1] https://ballerina.io/learn/getting-started/

**Comment by Nashaath** [comment]
Resolved via https://github.com/ballerina-platform/ballerina-www/pull/1059
