### ISSUE TITLE
[Quick Start] Setting up ballerina.home should be mentioned in the doc

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-www#881]
**Description:**
Refer https://github.com/ballerina-platform/ballerina-lang/issues/8328 for more details

**Comment by samgnaniah** [comment]
Closing this as per the discussion in the original ticket.

**Comment by rmsamitha** [comment]
> Closing this as per the discussion in the original ticket.

The original ticket had closed linking to this ticket, without any conclusion. 
Can I know where this is fixed in the docs?
