### ISSUE TITLE
[Quick Tour] Improvements In "DEPLOYING ON DOCKER" section

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-www#884]
**Description:**
In the "DEPLOYING ON DOCKER" section, "This needs to be added under the `endpoint http:Listener` .." text line is wrong. It should be "before the `endpoint ` ..."

![image](https://user-images.githubusercontent.com/7569427/41216830-8bf188de-6d73-11e8-905d-65e84b781567.png)

And we have to add a Tip after the sample code: 
"On windows PC's make sure the docker runs with linux containers and in the general settings, "Expose daemon on tcp://localhost:2375 without TLS" should be ticked (enabled). For more details check [https://github.com/ballerinax/docker/blob/master/samples/README.md](https://github.com/ballerinax/docker/blob/master/samples/README.md)".

**Affected Product Version:**
v0.9.016

**OS, DB, other environment details and versions:**    
All

**Steps to reproduce:**
1. Navigate to: https://ballerina.io/learn/quick-tour/
2. Scroll down to "DEPLOYING ON DOCKER" section

**Comment by samgnaniah** [comment]
Added the note one Windows to this open PR: https://github.com/ballerina-platform/ballerina-www/pull/873.

Regarding the Docker configs, it should be after the endpoint listener AFAIK. Only @docker:Expose {} is added before. This is specified in this PR: https://github.com/ballerina-platform/ballerina-www/pull/873.

This is my code:

```ballerina
// A system package containing protocol access constructs
// Package objects referenced with 'http:' in code
import ballerina/http;
import ballerina/io;
import wso2/twitter;
import ballerina/config;
import ballerinax/docker;




endpoint twitter:Client twitter {
   clientId: config:getAsString("consumerKey"),
   clientSecret: config:getAsString("consumerSecret"),
   accessToken: config:getAsString("accessToken"),
   accessTokenSecret: config:getAsString("accessTokenSecret")
};

@docker:Expose {}

// A service endpoint represents a listener
endpoint http:Listener listener {
    port:9090
};


// Docker configurations
@docker:Config {
    registry:"registry.hub.docker.com",
    name:"helloworld",
    tag:"v1.0"
}
@docker:CopyFiles {
    files:[
        {source:"./twitter.toml", target:"/home/ballerina/conf/twitter.toml", isBallerinaConf:true}
    ]
}


@http:ServiceConfig {
   basePath: "/"
}

// A service is a network-accessible API
// Advertised on '/hello', port comes from listener endpoint
service<http:Service> hello bind listener {

    @http:ResourceConfig {
    methods: ["POST"],
    path: "/"
    }

    // A resource is an invokable API method
    // Accessible at '/hello/sayHello
    // 'caller' is the client invoking this resource 
    sayHello (endpoint caller, http:Request request) {

        string status = check request.getTextPayload();

        twitter:Status st = check twitter->tweet(status, "", "");


        // Create object to carry data back to caller
        http:Response response = new;

        response.setTextPayload("ID:" + <string>st.id + "\n");

        // Objects and structs can have function calls
        response.setTextPayload("Hello Ballerina!\n");

        // Send a response back to caller
        // Errors are ignored with '_'
        // -> indicates a synchronous network-bound call
        _ = caller -> respond(response);
    }
}
```

**Comment by jeradrutnam** [comment]
@samgnaniah - Yes that will work too. But rephrasing should be "after" right, Not "under"? Because it will give the impression that we should put the code block inside the `endpoint http:Listener ...` block. WDYT?

And I feel it will be easy if we ask to copy and paste the whole block to one location rather asking to break and paste on 2 places. 

Else we need to keep the code blocks separate and ask to paste the block separately on each places. WDYT?

This is how my code block looks like,

![image](https://user-images.githubusercontent.com/7569427/41220949-6e718388-6d80-11e8-90ba-ffc778eb59f1.png)

**Comment by samgnaniah** [comment]
+1. Changed the PR to say 'after': https://github.com/ballerina-platform/ballerina-www/pull/873

I got an error when I kept the code together. It only worked after I moved the @docker:Expose {} before.
