### ISSUE TITLE
Custom client connector should implement getCallerActions and not getClient

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-www#890]
**Description:**
The second step of implementing the client connector claims as below [1]. 
' 2) Create an object with an init() and getClient() function.'

But we actually need to implement **getCallerActions() function instead of getClient()** function.

[1] https://ballerina.io/learn/how-to-extend-ballerina/
**Suggested Labels:**
bug

**Comment by Nashaath** [comment]
This is already fixed.
