### ISSUE TITLE
404 response for Visual Studio marketplace link

### ISSUE THREAD

**Issue by sahanruwanga** [ballerina-platform/ballerina-www#961]
**Description:**

There is a link to install ballerina plugin for VSC as [marketplace](https://marketplace.visualstudio.com/items?itemName=WSO2.Ballerina)  in https://github.com/ballerina-attic/plugin-vscode under the section of Installing. But it always gives 404 NOT FOUND response. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
@sahanruwanga we do not carry out active development in the particular repository currently and you can find the active repo at https://github.com/ballerina-platform/ballerina-lang and please use this link for [marketplace](https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina)
