### ISSUE TITLE
[Ballerina Quick Tour – Community Engagement]  Issue in main.bal code in calculator package

### ISSUE THREAD

**Issue by Sathiyakugan** [ballerina-platform/ballerina-www#965]
![42214251-9cb58f28-7ed8-11e8-909a-06de1b3575d7](https://user-images.githubusercontent.com/25485726/42218041-f3942226-7ee4-11e8-83a6-f1ed762eaf1b.png)

```
error: ./main.bal:32:24: undefined function 'add'
error: ./main.bal:35:24: undefined function 'subtract'
```

I got these erroe when running the main.bal

**Comment by ldclakmal** [comment]
@Sathiyakugan You get this issue because of exectuting `ballerina run main.bal`. As per the guidlines you should execute `ballerina run calculator` and run the calculator package. Please refer 5th and 6th steps of the guideline you followed.

**Comment by anupama-pathirage** [comment]
@Sathiyakugan Closing this issues as per the above comment. Please re-open if you have any concerns.

**Comment by Sathiyakugan** [comment]
Thanks a lot for the response . I resolve my problem.
