### ISSUE TITLE
[WSO2/twitter] error in match operation code example of 'tweet' function

### ISSUE THREAD

**Issue by prabhashthere** [ballerina-platform/ballerina-www#969]
**Description:**
wso2/twitter tutorial at BallerinaCentral
2nd line of match operation code example of 'tweet' function
error: unknown type 'Status'
https://central.ballerina.io/wso2/twitter#Client-tweet

**Affected Product Version:** 
Ballerina version: 0.975.0
**OS, DB, other environment details and versions:**    
OS: Ubuntu
**Steps to reproduce:**
can be fixed by modifying the 2nd line of the example code as follows,
twitter:Status twitterStatus => {
**Related Issues:**
no

**Comment by ldclakmal** [comment]
Fixes https://github.com/wso2-ballerina/package-twitter/pull/61
