### ISSUE TITLE
Ballerina Quick Tour - Calculator - main.bal 

### ISSUE THREAD

**Issue by PradeepaJey1** [ballerina-platform/ballerina-www#970]
### The ballerina/io import doesn't work in the composer, giving the error " extraneous input '/' "

```
package calculator;

**import ballerina/io;**

function main(string... args) {

    int c = 0;
    while ( c != 5) {
        // print options menu to choose from
        io:println("Select operation.");
        io:println("1. Add");
        io:println("2. Subtract");
        io:println("3. Multiply");
        io:println("4. Divide");
        io:println("5. Exit");

        // read user's choice
        string choice = io:readln("Enter choice 1 - 5: ");
        int c = check <int>choice;

        if (c == 5) {
            break;
        }

        // Read two numbers from user to be used for calculator operations
        var input1 = io:readln("Enter first number: ");
        float a = check <float>input1;
        var input2 = io:readln("Enter second number: ");
        float b = check <float>input2;

        // Execute calculator operations based on user's choice
        if(c == 1) {
            io:print("Add result: ");
            io:println(add(a, b));
        } else if(c == 2) {
            io:print("Subtract result: ");
            io:println(subtract(a, b));
        } else {
            io:println("Invalid choice");
        }   
    }
}
```

**Comment by nadeeshaan** [comment]
@PradeepaJey1 what's the ballerina version you are trying?

**Comment by ThejanRupasinghe** [comment]
@nadeeshaan  Package declaration line is auto-generated by the composer and without the package declaration `add` and `subtract` functions get undefined.
Ballerina version - 0.975.1

**Comment by HishanIndrajith** [comment]
I got a syntax error while the package declaration is there. 
![image](https://user-images.githubusercontent.com/31063882/42414920-e9b195c8-825d-11e8-956d-9390244bef68.png)
Error says extraneous input 'import'
When the  package declaration is removed, the syntax error is removed.
But there is an execution error coming when trying to execute the command 'ballerina run calculator' as follows 
![image](https://user-images.githubusercontent.com/31063882/42414934-61fb53d4-825e-11e8-81bb-03af3f1afc96.png)

**Comment by nadeeshaan** [comment]
@HishanIndrajith @ThejanRupasinghe This package name auto-generation has been fixed with the following https://github.com/ballerina-platform/ballerina-lang/issues/9437

**Comment by anupama-pathirage** [comment]
@HishanIndrajith  @ThejanRupasinghe Closing this issue as per the above comment. If you have further queries, please feel free to reopen this issue or create a new one.
