### ISSUE TITLE
[Ballerina Quick Tour – Community Engagement] compilation error in client.bal for calculator service

### ISSUE THREAD

**Issue by renuka-fernando** [ballerina-platform/ballerina-www#973]
**Description:**
Compilation error in client.bat file
`error: .\client.bal:17:20: not enough arguments in call to 'post()'
compilation contains errors`

**Affected Product Version:**
Ballerina 0.975.1

**OS, DB, other environment details and versions:**    
Windows 10, Java(TM) SE Runtime Environment (build 1.8.0_172-b11)

**Steps to reproduce:**
Created client.bal file in parent directory
Pasted the code
Run `ballerina run client.bal`

**Following Resolved**
Change line 17
From `var response = clientEndpoint->post("/calculator/operation", request = req);`
To `var response = clientEndpoint->post("/calculator/operation", req);`

**Comment by anupama-pathirage** [comment]
Duplicate issue https://github.com/ballerina-platform/ballerina-www/issues/964 This is fixed with 
https://github.com/ballerina-platform/ballerina-www/pull/967 and will be updated in the web site with 0.980.0 release
