### ISSUE TITLE
If try to write the first import statement, completions will not work. This is due to a limitation in the Completion error strategy and needs to revisit.

### ISSUE THREAD

**Issue by Chathura941010890** [ballerina-platform/ballerina-www#975]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
@Chathura941010890 Can you please provide the below details on this issue.

- What is the tool (IDEA plugin, VSCode plugin or composer) which gives this issue?
- What is the ballerina version you are using?
- Any code which can be used to reproduce this issue?

**Comment by nadeeshaan** [comment]
This issue has been already fixed in the latest master. Hence closing the issue.
