### ISSUE TITLE
windows compile is not work

### ISSUE THREAD

**Issue by suwendrarms** [ballerina-platform/ballerina-www#979]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by yohanym95** [comment]
WHAT IS A VERSION OF BALLERINA ,YOU USE?

**Comment by anupama-pathirage** [comment]
@suwendrarms We are closing this issue as we don't have enough information to reproduce the issue. Please feel free to reopen or create a new issue if you still have the issue.
