### ISSUE TITLE
variable c have been declared twice in main.bal causing scope clash.

### ISSUE THREAD

**Issue by MadhurangaWije** [ballerina-platform/ballerina-www#980]
**Description:**

Incorrect variable definition on the main.bal code example provided in the **Ballerina Quick Tour – Community Engagement** under "**Create a New Package**" sub heading.

the variable int c, have been defined two places in line number 5 and line number 17 of **main.bal** a way its scope gets clashed.
**Suggested Labels:**

Redefined a variable already defined

**Suggested Assignees:**

Quick tour documentation writer.

 

**Steps to reproduce:**
simply remove the int part from the line 17, int c.
In that line its supposed to assigned the input number to the variable c which have been defined outside the while loop. its incorrect to redefine a new int variable there.

**Related Issues:**

As a result of this issue. the entire file won't be compile. hence we wouldn't be able to implement the calculator functionality.

**Comment by anupama-pathirage** [comment]
Duplicate issue of https://github.com/ballerina-platform/ballerina-www/issues/963, hence closing this.
