### ISSUE TITLE
redeclared symbol 'main'

### ISSUE THREAD

**Issue by MadhurangaWije** [ballerina-platform/ballerina-www#981]
**Description:**

When you go through the **Ballerina Quick Tour – Community Engagement** guidelines and first you implement the calculator to run as a general application without using web service end implementation. later after when we make the calculator service and then calculator next, then it ll cause an error when we try to run. its because main(string... args) function is defined in two files under the calculator package. therefore it ll show an error saying redeclared symbol 'main'. **The problem is this is not mentioned clearly in the guide**. 

**Suggested Assignees:**

**Ballerina Quick Tour – Community Engagement**  guideline writers.

**Steps to reproduce:**
We cannot run client program keeping the first made **main.bal** file because that also contains main().
Therefore we have to either remove or comment out in order to run the client.

**Comment by HishanIndrajith** [comment]
I kept the client.bal outside the calculator directory to overcome the problem

**Comment by yohanym95** [comment]
when i build a calculator then give a error like this.then i change c varibale like this,
c = check <int>choice;
but nothing happend.
error: sami/calculator:0.1.0\main.bal:3:1: redeclared symbol 'main'
compilation contains errors

**Comment by namila007** [comment]
@yohanym95 check whether there are more than one `main` functions inside calculator directory. you need to keep the `client.bal` on root of calculator directory
