### ISSUE TITLE
not enough arguments in call to 'post()'

### ISSUE THREAD

**Issue by MadhurangaWije** [ballerina-platform/ballerina-www#982]
**Description:**

Cannot compile and run the **client.bal** file which have been provided under the topic CREATE A CLIENT FOR CALCULATOR SERVICE in the guide. the line 18 gives an error. when we replace the `request=req`  which is the second argument of the post( ) with just `req`, then it works fine.
**Suggested Labels:**

post( ), not enough arguments, request, req

**Suggested Assignees:**

**Ballerina Quick Tour – Community Engagement** guide writer.

**Steps to reproduce:**
replace the `request=req`  which is the second argument of the post( ) with just `req`

**Comment by chamil321** [comment]
Related [PR](https://github.com/ballerina-platform/ballerina-www/pull/967) is merged to the master. Hence closing the issue
