### ISSUE TITLE
wso2/github4  giving field 'license' doesn't exist on type 'Repository' error for requests on repositories 

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-www#985]
When trying to execute functions listed in wso2/github4, the functions give a 'license' doesn't exist on type 'Repository' error for all the requests even though a license is available for the specific repository or repository list.   

Experimented Ballerina Version:  0.975.1

**Comment by anupama-pathirage** [comment]
Created https://github.com/wso2-ballerina/package-github/issues/49 to track this, hence closing this issue.
