### ISSUE TITLE
redeclaration issue

### ISSUE THREAD

**Issue by mihinduranasinghe** [ballerina-platform/ballerina-www#988]
In the quick tour there is a issue when creating main.bal file. There already declared c in the begining and again it has bee declared as another variable 
int c = check <int>choice 
in this line. Among them One of the c variable should be changed as another variable name.

**Comment by anupama-pathirage** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-www/issues/984, hence closing this issue.
