### ISSUE TITLE
[Quick Tour - CREATE A CLIENT FOR CALCULATOR SERVICE] syntax error in the documentation

### ISSUE THREAD

**Issue by shyaman** [ballerina-platform/ballerina-www#996]
**Description:**
In the documentation, code of the calculator client section in the quick tour contains a syntax error

>     var response = clientEndpoint->post("/calculator/operation", request = req);

**Suggested Labels:**
Type/Docs

**Affected Product Version:**
Ballerina Version - 0.975.1

**Resolve:**
Replace above syntax as follows

>     var response = clientEndpoint->post("/calculator/operation", req);

**Comment by riyafa** [comment]
Already fixed in https://ballerina.io/community-program/index.html
